service:
  name: "catalog-service"
  port: ":8080"

postgres:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbName: "catalog_db"
  sslMode: "disable"

jwt:
  secret: "Xrunimz&69"